Add word count library example
husky-team/pyhusky pull request #29
Opened 2017-05-04 07:14 UTC by Yuzhen11

2017-05-05 03:11 UTC, kygx-legend requested changes
Please follow the readme again.

2017-05-05 03:11 UTC, kygx-legend commented on backend/python_connector.cpp
> +        popen(("python -m python.pyhusky.backend.python_backend " + std::to_string(lid) + " " + std::to_string(gid) + " " +
No need to change this. By default, `$PYTHONPATH` in readme includes python dir.

2017-05-05 03:11 UTC, kygx-legend commented on backend/register.cpp
> +#include "backend/library/word.hpp"
wrong order?

2017-05-05 03:11 UTC, kygx-legend commented on python/pyhusky/backend/library/functional.py
> +from python.pyhusky.backend.globalvar import GlobalVar, GlobalSocket, OperationParam, GlobalN2NSocket
ditto

2017-05-05 03:12 UTC, kygx-legend commented
Ref #28

2017-05-05 03:19 UTC, Yuzhen11 commented on python/pyhusky/backend/library/functional.py
> +from python.pyhusky.backend.globalvar import GlobalVar, GlobalSocket, OperationParam, GlobalN2NSocket
I don't want to use the installed one. I met some problem during re-installation. The package cannot update. So instead I directly use the raw python file in the folder.

2017-05-05 03:26 UTC, kygx-legend commented on python/pyhusky/backend/library/functional.py
> +from python.pyhusky.backend.globalvar import GlobalVar, GlobalSocket, OperationParam, GlobalN2NSocket
Certainly yes for development. Then you don't need to use the installed method. A very simple way is to set env `$PYTHONPATH` like `$ export PYTHONPATH=$PYHUSKY_ROOT/python` and this is compatible with `import pyhusky.*`. Adding `python.pyhusky` is too ugly.

2017-05-05 03:28 UTC, kygx-legend commented on python/pyhusky/backend/library/functional.py
> +from python.pyhusky.backend.globalvar import GlobalVar, GlobalSocket, OperationParam, GlobalN2NSocket
Sorry for that I don't remember to add this into readme.

2017-05-07 00:57 UTC, kygx-legend approved these changes

2017-05-07 00:58 UTC, merged